---
title: Niall Kenny
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.niallkenny.com
description: Director based in London specialising in documentaries, fashion film
  and branded content.
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Niall Kenny
showreel: 284202755
job: DP / Director
email: info@niallkenny.com
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  instagram: https://www.instagram.com/niallkenny/
  vimeo: https://vimeo.com/niallkenny
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  enabled: true
  per_page: 100
imgix:
  source: niall-kenny.imgix.net
